version: '3'
services:
  api:
    container_name: bowser-api
    image: furmanov/bowser:1
    restart: always
    build: .
    ports:
      - '6105:6105'
    links:
      - mongo
      - redis
    env_file:
      - .env
    environment:
      - REDIS_PORT=6379
      - REDIS_HOST=redis
      - MONGODB_HOST=mongodb://mongo:27017/hotel-docker
  mongo:
    container_name: bowser-mongo
    image: 'mongo:4'
    ports:
      - '27017:27017'
  redis:
    container_name: bowser-redis
    image: 'redis:5'
    ports:
      - '6379:6379'
