version: '3'
services:
  api:
    container_name: bowser-api-main
    image: furmanov/bowser
    restart: always
    build: .
    ports:
      - '6105:6105'
    links:
      - mongo
      - redis
    depends_on: 
      [mongo,redis]
    env_file:
      - .env
    environment:
      - REDIS_PORT=redis://redis:6379
      - MONGODB_HOST=mongodb://mongo:27017/hotel
  mongo:
    container_name: bowser-mongo
    image: 'mongo:4'
    ports:
      - '27017:27017'
  redis:
    container_name: bowser-redis
    image: 'redis:5'
    ports:
      - '6379:6379'
