defaults: &defaults
  #working_directory: ./circleci
  docker:
    - image: circleci/node:10

version: 2
jobs:
  prepare:
    <<: *defaults
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
      - run:
          name: Install Dependencies
          command: yarn install --frozen-lockfile
      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
      - persist_to_workspace:
          root: .
          paths:
            - node_modules
  build:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run: yarn build
      - persist_to_workspace:
          root: .
          paths:
            - build
  unit:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run: yarn test
  e2e:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run: yarn e2e
  lint:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run: yarn lint
workflows:
  version: 2
  build_accept_deploy:
    jobs:
      - prepare
      - lint:
          requires:
            - prepare
      # - build:
      #     requires:
      #       - lint
      # - unit:
      #     requires:
      #       - build
      # - e2e:
      #     requires:
      #       - build
