defaults: &defaults
  #working_directory: ./circleci
  docker:
    - image: circleci/node:10

version: 2
jobs:
  prepare:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Update NPM
          command: 'sudo npm install -g npm@latest'
      - restore_cache:
          name: Restore NPM Package Cache
          keys:
            - dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Install Dependencies
          command: npm install
      - save_cache:
          name: Save NPM Package Cache
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - node_modules
      - persist_to_workspace:
          root: .
          paths:
            - node_modules
  build:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run: npm run build
      - persist_to_workspace:
          root: .
          paths:
            - build
  unit:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run: npm run test
  e2e:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run: npm run e2e
  lint:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run: npm run lint
workflows:
  version: 2
  build_accept_deploy:
    jobs:
      - prepare
      - lint:
          requires:
            - prepare
      # - build:
      #     requires:
      #       - lint
      # - unit:
      #     requires:
      #       - build
      # - e2e:
      #     requires:
      #       - build
