defaults: &defaults #working_directory: ./circleci
  docker:
    - image: circleci/node:10
    - image: circleci/mongo:latest
    - image: circleci/redis:5
      environment:
        REDIS_PORT: 6379
        REDIS_HOST: 127.0.0.1
version: 2
jobs:
  docker:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
         at: .
      - setup_remote_docker
      -run:
         name: Attach Docker
         command: 'sudo systemctl start docker'
  prepare:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Update NPM
          command: 'sudo npm install -g npm@latest'
      - restore_cache:
          name: Restore NPM Package Cache
          keys:
            - dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Install Dependencies
          command: npm install
      - save_cache:
          name: Save NPM Package Cache
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - node_modules
      - persist_to_workspace:
          root: .
          paths:
            - node_modules
  build:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Build Artefact
          command: npm run build
      - persist_to_workspace:
          root: .
          paths:
            - build
  lint:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Code Linting
          command: npm run lint
  unit:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Run Unit Tests
          command: npm run test
  e2e:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Run End-to-End Tests
          command: npm run e2e
workflows:
  version: 2
  build_accept_deploy:
    jobs:
      - docker
      - prepare:
          requires:
            - docker
      - lint:
          requires:
            - prepare
      # - build:
      #     requires:
      #       - lint
      # - unit:
      #     requires:
      #       - build
      - e2e:
          requires:
            - lint
